openapi: 3.1.0
info:
  version: '0.0.4-beta'
  title: 'Anthic Trade API'
  description: |
    The Anthic Trade API allows traders to view order books of various token pairs and trade against these order books.

servers:
  - url: 'https://taker-api.staging.anthic.io/trade'
paths:
  "/tokens":
    get:
      summary: Get Supported Tokens
      description: Get a list of supported tokens and information about each token
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokensResponse"
              example:
                tokens:
                  - symbol: "XRD"
                    resource_address: "resource_rdx1tknxxxxxxxxxradxrdxxxxxxxxx009923554798xxxxxxxxxradxrd"
                  - symbol: "xUSDC"
                    resource_address: "resource_rdx1t4upr78guuapv5ept7d7ptekk9mqhy605zgms33mcszen8l9fac8vf"
  "/token_pairs":
    get:
      summary: Get Supported Token Pairs
      description: Get a list of supported tokens and information about each token
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenPairsResponse"
              example:
                token_pairs:
                  - base: "XRD"
                    quote: "xUSDT"
                  - base: "xwBTC"
                    quote: "xUSDC"
  "/accounts":
    get:
      summary: Get Accounts
      description: |
        Retrieve info about the current user's accounts. Must be authenticated.
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountsResponse"
  "/order_book":
    get:
      summary: Get Order Book
      description: |
        Get the order book of a token pair
      parameters:
        - in: query
          name: base
          schema:
            type: string
            example: "XRD"
          description: The resource address for the base token
        - in: query
          name: quote
          schema:
            type: string
            example: "xUSDC"
          description: The resource address for the quote token
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderBookResponse"
              example:
                pair:
                  base: "XRD"
                  quote: "xUSDC"
                bids:
                  - price: "0.015"
                    quantity: "1000"
                  - price: "0.0146"
                    quantity: "1500"
                  - price: "0.01301"
                    quantity: "3200"
                asks:
                  - price: "0.0155"
                    quantity: "1000"
                  - price: "0.017"
                    quantity: "1200"
  "/orders":
    post:
      summary: Submit an Order
      description: |
        Submit an order to be filled and executed on-ledger
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubmitOrderRequest"
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubmitOrderResponse"

components:
  schemas:
    TokensResponse:
      type: object
      required:
        - tokens
      properties:
        tokens:
          type: array
          items:
            $ref: "#/components/schemas/TokenDefinition"
    TokenPairsResponse:
      type: object
      required:
        - token_pairs
      properties:
        tokens:
          type: array
          items:
            $ref: "#/components/schemas/TokenDefinition"
    AccountsResponse:
      type: object
      required:
        - accounts
      properties:
        accounts:
          type: array
          items:
            $ref: "#/components/schemas/Account"
    OrderBookResponse:
      type: object
      required:
        - pair
        - base
        - quote
        - bids
        - asks
      properties:
        pair:
          $ref: "#/components/schemas/TokenPair"
        bids:
          type: array
          items:
            $ref: "#/components/schemas/LimitOrder"
        asks:
          type: array
          items:
            $ref: "#/components/schemas/LimitOrder"
    SubmitOrderRequest:
      type: object
      required:
        - signed_partial_transaction
      properties:
        signed_partial_transaction:
          type: string
    SubmitOrderResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: bool
        success_response:
          type: "#/components/schemas/NewOrderSuccessResponse"
        error_response:
          $ref: "#/components/schemas/NewOrderErrorResponse"
    TokenDefinition:
      type: object
      properties:
        symbol:
          type: String
        resource_address:
          type: String
    TokenPair:
      type: object
      required:
        - base
        - quote
      properties:
        base:
          type: string
        quote:
          type: string
    LimitOrder:
      type: object
      required:
        - price
        - quantity
      properties:
        price:
          type: String
        quantity:
          type: String
    NewOrderSuccessResponse:
      type: object
    NewOrderErrorResponse:
      type: object
      required:
        - reason
      properties:
        reason:
          type: String
    Account:
      type: object
      required:
        - address
        - instamint_credit
        - balances
      properties:
        address:
          type: string
        instamint_credit:
          type: string
        balances:
          type: array
          items:
            $ref: "#/components/schemas/ResourceBalance"
    ResourceBalance:
      type: object
      required:
        - symbol
        - balance
      properties:
        symbol:
          type: string
        balance:
          type: string
